### ISSUE TITLE
Build Problems on Stellarmate OS

### ISSUE THREAD

**Issue by kneo** [kneo/indi-bresserexos2#2]
Kevin, any help with this? Tried to install on the Stellarmate OS, did a few adjustments on you guidelines on how to install it but I'm stucked here.. on the CMake .. 

![20210405_014620](https://user-images.githubusercontent.com/80964892/113528782-2eb07b80-95b1-11eb-8b1c-91799b8d015f.jpg)

_Originally posted by @FocusAG in https://github.com/kneo/indi-bresserexos2/issues/1#issuecomment-813140431_

**Comment by kneo** [comment]
@FocusAG
I shifted it in a new issue, since it is off topic in the other issue.

It seems, the development headers are not installed. Please make sure `libindi-dev` is installed.

**Comment by FocusAG** [comment]
Hi Kevin,, yup it's installed.. I've just checked the libindi-dev and it's installed.. 
I just installed again in order to make sure of it.
Run the driver and same problem.

Cheers,
Cesar

**Comment by kneo** [comment]
It states, that it can not find some version header, so maybe the install location on Stellarmate OS deviates from Astroberry. 

Please run:

`find / -name "indiversion.h" 2>/dev/null`

and:

`find / -name "libindi*.so" 2>/dev/null` 

and provide the output here. We may have to add an additional variable to the cmake call in order to tell it where to find the indi headers and may be libraries.

**Comment by FocusAG** [comment]
Just tried this evening the codes that you provided.. here you have it ;)

**Comment by FocusAG** [comment]
![Uploading 20210406_231700.jpg…]()

**Comment by kneo** [comment]
the link is not working.

**Comment by FocusAG** [comment]
![20210406_231700](https://user-images.githubusercontent.com/80964892/113891800-f24d6d00-97b4-11eb-9f07-244819d0456c.jpg)

Here it is

**Comment by kneo** [comment]
Hm, I can not read why it fails, since this is exactly how my paths are. There seems to be something wrong with the  cmake script for your linux distribution.

Maybe there are some hints in these logfiles:
`/home/stellarmate/indi-bresserexos2/build/CMakeFiles/CMakeOutput.log`
`/home/stellarmate/indi-bresserexos2/build/CMakeFiles/CMakeError.log`
the last two lines on your first screenshot.

Could you provide these?

**Comment by FocusAG** [comment]
[CMakeError.log](https://github.com/kneo/indi-bresserexos2/files/6274146/CMakeError.log)
[CMakeOutput.log](https://github.com/kneo/indi-bresserexos2/files/6274147/CMakeOutput.log)

Here you have it.. If you want, I could provied to you a copy of the Stellarmate software in order to you to check potential errors..

**Comment by kneo** [comment]
hm this still does not help.
However you could open the projects `CMakeLists.txt` in a text editor and comment out this line:
`find_package(INDI REQUIRED)`
by adding a `#` in front of it:
`#find_package(INDI REQUIRED)`
this should override the Indi detection, and may at least enable you to build the driver.
I added this to provide a troubleshooting information to the user. But its not strictly necessary.

Once the its integrated in the 3rd party drivers, this happens via the normal build system anyways.

**Comment by FocusAG** [comment]
Ok Kevin.. I'll tried that tonight and keep you posted if you don't mind.

Anothe question: Do you think there's a way of improving the accuracy of the Goto?

Cheers,

Cesar

**Comment by kneo** [comment]
> Anothe question: Do you think there's a way of improving the accuracy of the Goto?
I can only think of the ways the Handbox allows, eg. backlash correction, good alignment (star/polar) utilizing the serial protocol there is no further improvement, unfortunately. That is without touching the software of the handbox. 

When using the goto, I noticed that it was quite accurate for my level of knowledge. If you have a stary night you could try using the sync function: after setting up and alignment, make a rough goto, correct the pointing using the handbox, then use the sync function in Kstars, to tell the mount the actual pointing coordinates. After that it should be rather accurate. However if you intent to do "deeper" sky observation this might not be sufficient. I can not really vouch for the accuracy, since real live testing has been impossible for months.

Tips I can give are: Make sure your polar scope is center adjusted it was quite of in my mount, even though the vendor said everything was calibrated - spoiler alert: it wasn't! Make a good polar alignment using a polar finder app, to nail Polaris. With this I did not notice any drift of the mount or stars, this may still be inaccurate because I had not had the chance to test my new camera gear, yet. 

But there is not much else to be done, unless you'd like to invest into a better mount.

**Comment by FocusAG** [comment]
Gotcha Kevin,

Actually It was one of the things that I did a few months ago, when I put the hypothysit of one of the problems been the polar socpe not been colimated as it should, so I did myself. But you're probably right on start doing the alignment using software or a polemaster, anyway I think there's some bug on the two and three star alignment, because it gives after a doing it a small margin of error in the finder scpe, imagine that error on a higher magnification like I'm used to do.
I've used the sync of the handbox a few times, but works only up at some point, but the problems with that is doing deep sky objects, we can't see them at naked eye.
I'm planning to use her for deep sky, but like you said: if there's no major breakthrough in the firmware, the driver it only can go up to somepoint. This is a very primitive protocol.

Do you think if Bresser gives the firmware code, we could change it and turn her a better solition? Or just simply forget all of this work? I wasn't ready enough to give up on her..

Best regards,

Cesar

**Comment by kneo** [comment]
> Actually It was one of the things that I did a few months ago, when I put the hypothysit of one of the problems been the polar socpe not been colimated as it should, so I did myself. 

Thats a good start, I guess.

> But you're probably right on start doing the alignment using software or a polemaster, [...]

I didn't mean that, I meant an app for you phone which shows where Polaris should be in polar scope, you then turn the "clock" to this position (the vertical line from the center cross) and then adjust Azimuth and Altitude of your mount such that the Polaris is inside the small circle. This should be optimal. Also don't trust the numbers on the display, I elaborated that in the Troubleshooting.md.

> I've used the sync of the handbox a few times, but works only up at some point, but the problems with that is doing deep sky objects, we can't see them at naked eye.

Not in the handbox, in kstars. Take a cross eye peace, center your object with the Handbox and than tell via kstars to sync. This should align everything quite well. I tested it with Mars and then slewed to M43 which was roughly centered in view. I see the handbox just as a fancy controller, and do not use most of its functionality. A lot of it does not make any sense to me, Why would I need all these astronomic objects when I have a dedicated software? They just sound good on a marketing sheet. They could have done better with less.

> I'm planning to use her for deep sky, but like you said: if there's no major breakthrough in the firmware, the driver it only can go up to somepoint. This is a very primitive protocol.

I bet you can do deep sky with that, but however expensive your gear is, all the professionals on Youtube rely on plate solving at some point, so I think the build in goto is not going to cut it for everything.

Further: There is work done reverse engineering the software, the guy (spitzbube) wants to replace it altogether, once its understood. You'll find the link in the main readme, but he has not much of a documentation yet. 
However I can not simply flash the firmware, there are several older(?) versions of the Handbox PCB released which can be flashed, mine is not the type. Which is why I intent to use the reverse engineered knowledge to replace the handbox with my own, but one step at a time. I also have a focus motor in the working queue, so a stable driver has to suffice for now.

> Do you think if Bresser gives the firmware code, we could change it and turn her a better solition? 

If we had the code it would take some months and we had a way better solution for it.
However Bresser just relabels and distributes this stuff, and apparently does not develop it. 
The PCB says: "JOC SkyVision", where JOC is some big Chinese company owning Bresser.
([See here](https://github.com/Spitzbube/EXOS-2_GoTo_HandController/releases/tag/v2.3))
So I doubt they are even able to provide the code.
Its unfortunate, because with the Explore Scientific version of this mount, you can get the code (ES has the same mother company), its advertised as such at least.
However from the looks of it, I like the Bresser version better.
The ES version looks like a bunch of motors duct taped to the mount, no casing at all.
I wonder if these things would survive a humid night.

> Or just simply forget all of this work? I wasn't ready enough to give up on her..

It is not all that bad, but I can understand people who feel ripped off when confronted with this mount.
A lot of people want fast results, and this thing can be quite frustrating, not just by obnoxiously beeping.
Its actually only the software which is severely bad, the rest is quite OK at least for my purpose.
There are some people out there who are willing to improve this mount, so its not dead yet. 
I'm not willing to resign yet either, I have ways and means to make it better.

**Comment by FocusAG** [comment]
Hello Kevin.. any ideas for this?

![20210409_231747](https://user-images.githubusercontent.com/80964892/114253333-53359a80-9999-11eb-872e-f147a1024135.jpg)

**Comment by kneo** [comment]
Please run:

find / -name "julian_day.h" 2>/dev/null

to find out if these header file exists. Please provide the output.

If it does not exist please install:

`sudo apt-get install libnova-0.16-0 libnova-dev libnova-dev-bin`

and try again.

**Comment by FocusAG** [comment]
Hello Kevin.. well it wasn't installed, I've already done it and then went to this on the CMake - - build .

![20210411_013729](https://user-images.githubusercontent.com/80964892/114289343-a3c6f980-9a66-11eb-8b11-47669b42943d.jpg)

**Comment by kneo** [comment]
Hm,
it looks like you are close to the goal.

Could you open a Terminal in your home directory, simply starting it using the menu should suffice. 

Then please run these commands:

> `strings /lib/arm-linux-gnueabihf/libpthread.so.0 | grep GLIBC > glibc.log`

and

> `dpkg -l | grep libc > package_glibc.log`

These should create two files *.log files in your home directory. Please attach these files for your reply. 

It seems like you have an "old" system, you may fix it by running these commands:

> `sudo apt-get update`

and after this concluded:

> `sudo apt-get dist-upgrade`

This should update your system and take some time.
After manually rebooting the system, retry the build process, which should hopefully succeed then.

**Comment by FocusAG** [comment]
Hello again Kevin.. I've tried the commands that you provided last night, everything the same. One of the things that I do after I install the OS is to do the updates, but I did it again after what you've told me.. same situation.. check it:

![20210411_175002](https://user-images.githubusercontent.com/80964892/114395757-462ccd00-9b8c-11eb-84dc-f3782860070d.jpg)

![20210411_175029](https://user-images.githubusercontent.com/80964892/114395812-5b096080-9b8c-11eb-8e7c-3c0f0449283b.jpg)

![20210411_175055](https://user-images.githubusercontent.com/80964892/114395912-74aaa800-9b8c-11eb-875d-474dc937c4e7.jpg)

**Comment by kneo** [comment]
open the CMakeLists.txt from before,
go to the line:
set(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR})

and add new line with:
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -pthread")

and retry.

**Comment by FocusAG** [comment]
Great news Kevin.. finally the driver is up and running on StellarMate OS. Thank you for you help and patience.

Regards,

Cesar

**Comment by kneo** [comment]
Finally, I'm glad!

Would you be so kind, to provide the steps you had to do on stellarmate, to get it running? I mean everything outside of this issue so I can update the documentation.

Regards,
Kevin

**Comment by FocusAG** [comment]
I can described the process was I write it down in a txt file for future instellations if you want. Oh Bresser also contacted me this morning regarding my request and some updates of the GoTo system.
They told me they are writting a new firmware for the handcontroller in order to solve some issues of the mount, one of them is the accuracy of the GoTo and the two star alignment and three. Another thing about it, they re building to a driver for ASCOM only. They are not giving support on INDI, so for users like me and you, we need to realy on yours. Let's hope this new firmware can solve some of this situation.

**The steps:**

Close everything when starting the Stellarmate OS and go for the terminal and run this:

sudo apt-get update 

and after: 

sudo apt-get upgrade

restart the system after everything is installe, close all the apps on the startup and go for terminal again and write:

sudo apt-get install libindi1

sudo apt-get install libindi-dev

sudo apt-get install cmake build-essential

sudo apt install -y git

sudo apt-get install libnova-0.16-0 libnova-dev libnova-dev-bin

After all this software is installed, run:

sudo apt-get update

sudo apt-get upgrade

And reboot.. After the reboot open terminal and run:

git clone https://github.com/kneo/indi-bresserexos2.git

cd indi-bresserexos2

After this you need to open and new terminal and run:

sudo pcmanfm

This will open a new window and through that windows you need to change the permitions of the folder "indi.bresserexos2".
Go to the /home/stellarmate and right click on the "indi-bresserexos2" folder, do a right click on "properties", go to "select permitions" and change "change content" to "all". Every controll access should to to "all". Don't close anything just yet.
On the window where you are building the driver write it down:

mkdir build

And run it. After that go to the window where you changed the properties and change the "build" folder permitions to "all". Just doing the same steps that you did in the "indi-bresserexos2" folder. Doing a right click on the folder "build" and select "properties", select permitions and change "change content" to "all". Every controll access should to to "all". After that, close every window including terminal.
This step is super importante. Go to the forder "build" in the folder "indi-bresserexos2", and you need to change in every file inside her that you can edit (.txt files) and every line of command that says "... /home/astroberry/ ... " you need to replace the name "astroberry" with "stellarmate". It will be something like "... /home/stellarmate/ ... ". Remember every line of command on each txt file needs to be pointing to a "stellarmate" insted of astroberry. It will be a few lines and in a few files as well, just don't forget to save it.

After it go to the folder "indi-bresserexos2", and the file  CMakeLists.txt go to the line:

set(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR})

and add new line below with:

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -pthread"

Save it and go to the file "CMakeLists.txt" and with the text editor add this line bellow the first lines of command:

find_package(INDI REQUIRED)

by adding a # in front of it:

#find_package(INDI REQUIRED)

Safe it and open a new terminal running those lines of code:

strings /lib/arm-linux-gnueabihf/libpthread.so.0 | grep GLIBC > glibc.log

dpkg -l | grep libc > package_glibc.log

Then: 

sudo apt-get update

sudo apt-get dist-upgrade

And reboot after this. Then when the system pops up, close every app that started with it, and open terminal and run:

cd indi-bresserexos2

cd build

cmake ..

cmake --build .

sudo make install

Everything should be up and running after this. Just do a reboot of the system and you'lle have the driver running like a charm.
If you have any ideas to do this more simple to run in Stellarmate, it would be awsome. One of the things that I did to make it simple, was doing a copy of the driver already installed with the modifications on the files with the new lines of code, and insted of compile the folder again by downloading and go after all the modifications in the files, I just copy to the "/home" folder and installed the tools to compile the driver, run it and, saved me trouble of changing the .txt files all over again.

This was my process with your help. 
Regards, Cesar

**Comment by kneo** [comment]
> [...] Oh Bresser also contacted me this morning regarding my request and some updates of the GoTo system.
> [...]

This is some great news! May be I don't have to build my one controller after all!

> 
> **The steps:**
> [...]

Thank you very much, I see how I tailor this into the existing Documentation.

Closing the Issue since its resolved!
