### ISSUE TITLE
Da and RA are backwards 

### ISSUE THREAD

**Issue by spyda96** [kneo/indi-bresserexos2#4]
Loaded drivers and change locations on HBX to see if this would help but nothing. When I point west in the GOTO on kstars it moves east. Goto north it sews south.

**Comment by kneo** [comment]
Please provide a rough location so I can reproduce the bug.

**Comment by spyda96** [comment]
47:36:32.0 237:39:47.0 for site management
seattle washington for Kstars 
same for HBX

**Comment by spyda96** [comment]
I did some more trouble shooting I felt like this was more of a user error and not programming. because once I change my location in Kstars to china I had the correct RA and DA movement. 
did some more testing last night. 
power on mount  
adjust time 
adjust location
start ekos
start indi
when into site management lon 237.663 lat 47.6089
change site management to lon -122.629 lat 48.4953
check HBX corrected time(went back to home locations time zone)  and location (went back to home location china)
Once all steps above are done we have correct RA and DA movement. 
YAY!

**Comment by kneo** [comment]
This still might be a problem though, I'm unsure if its a driver error or a bug in the firmware. Both is possible! Apparently the issue occurs when your location is past the null meridian.
If you happen to be located eastwards the problem does not occur, which is why it never happened to me.

Its easy to determine if its a firmware bug: If you simply use the ASCOM driver and redoing your steps should reproduce the same behavior.

**Comment by spyda96** [comment]
Discovered another setting in the Configure Kstars menu for the INDI general setting, in the "Time & Location Updates" uncheck KStars update all devices time and locations.

By doing this I was able to connect to the HBX without having to change the Locations or Time zone settings every time I started a new connection with KStars to HBX.

**Comment by spyda96** [comment]
![image](https://user-images.githubusercontent.com/36378749/123180437-1e859b00-d440-11eb-8e31-113d16b2b5dc.png)

**Comment by kneo** [comment]
Hello, thats just a workaround: however it testifies against my driver. If it works with the handbox there can not be a firmware issue. Thus I have to look into it. I reopen and fix this, with the next driver update.

**Comment by stardog123** [comment]
Hello!
First I would like to thank you for making this driver. I used the mount for more than half a year and still wasn’t able to make it work even once. With your driver I was able to connect it and move it as well for the first time. 
however, I think I have the same problem as the person that oben this thread. I was trying to move the mount to the east, but it moved to the west.
I also had the problem that the mount did not respond to the software buttons in the „Mount Control“ window in EKOS. 
The mount also doesn’t slew a lot of times, when I am typing in coordinates. It only moves to targets that are really close to the parking position. Other than that it just doesn’t move at all.
I don’t know what I should submit as a report cough. As it doesn’t crash or tell me an error. EKOS tells me that the mount is slewing to the coordinates but nothing happens. 

thank you again for your tremendous effort and work. 
It really means a lot!

best regards

**Comment by stardog123** [comment]
As there is no good weather in the near future, I won't be able to report it correctly. I will report back however, once I am able to go back outside. 
I tried once during the day and the workaround from spyda96 seemed to make it work perfectly with no issues at all. I will know for sure, once I am in the field again.
That workaround seems to be the solution to my problems though.

**Comment by FocusAG** [comment]
Kneo.. I have a question regarding the updating of the driver..
I'm using stellarmate. When you do the update of the driver here on github, there is a way of updating her in the Stellarmate/Indi repository? A simple system update as we do time to time is enough to update the driver, or we need any extra commands to do it?

As said in this issue, the coordinates are changed, and in the Kstars in the INDI parameters. When the we select Kstars update all the devices (time and location), simply doesn't work, but if we select the Mount update Kstars, it works.. This is odd also and I don't know if you are aware.

Regards

Cesar

**Comment by kneo** [comment]
@FocusAG I intent to fix this in a special branch, to get it tested and later to integrate it into the indi 3rd party repository.

regarding: kstars, I'm not aware which corner case updates what, I usually test it in the mount settings window. When you initially connect to the mount it also updates (see above), I don't know where else there is a possibility to change settings. But I'll look into it ...

**Comment by kneo** [comment]
@FocusAG fyi: I added to latest source to the indi/3rdParty repository, if the pull request gets accepted, the new source should be available via your package manager soon.

**Comment by kneo** [comment]
I added some changes concerning time an location, in the latest release. I should also fix issues with wrong motion. It happened because, for one, the Timezone never was provided by the driver. This leads to a time difference -12 hours in any case. Since the handbox uses your provided local time and uses this and the timezone offset to calculate back the UTC time for astrometrics, miscalculations happened and may have caused issues. Also the location in west direction was buggy, since I converted these value wrong. Both of these issues are now resolved and should provide more reliability when using the driver.

_Checkout the latest version of the main branch to use these improvements. I also completed the pull request for the 3rd party driver repository, there deployment to Astroberry and Stellarmate should arrive shortly._

Clear skies!
