### ISSUE TITLE
Driver installed but not showing on indi manager

### ISSUE THREAD

**Issue by YardoDEVS** [kneo/indi-bresserexos2#7]
Hi, I just installed your driver to use my bresser with astroberry but the driver does not appears in indi webmanager. I have followed your install docs steps but after the driver says it's installed I can't view it throw indi webmanager. I'm using Astroberry Server 2.0.3 with latest distro updates. Any help please? Thanks in advance, cheers

**Comment by kneo** [comment]
Did you check out the main branch or the [dev_Ver0.900](https://github.com/kneo/indi-bresserexos2/tree/dev_Ver0.900) branch?

**Comment by YardoDEVS** [comment]
I wrote my microsd for the Raspberry 4 with the main Astroberry Server 2.0.3 image, sorry but I don't understand the difference betwen versions, I thought there was only one cooked version of the distro.

**Comment by kneo** [comment]
Its alright, you said you followed the install docs. So its the main branch.

could you check if these files exist:

- /usr/bin/indi_bresserexos2
- /usr/share/indi/indi_bresserexos2.xml

use a file manager or what ever to confirm.

**Comment by YardoDEVS** [comment]
Yes, these files are in these locations. The xml one contains plain text inside with the name of driver and version info, then I suppose the driver was created in good conditions too

**Comment by kneo** [comment]
could you open a terminal in the "build" directory and issue this command:

`indiserver -v ./indi_bresserexos2`

and post the output?

It should look like this: 

[troubleshooting](https://github.com/kneo/indi-bresserexos2/blob/main/Documentation/Troubleshooting.md#bugreport-provide-useful-debug-information)

and also blocks when running correctly, you have to use `[CTRL]+[C]` to 'kill' the program. This should at least make sure the driver in working order.

Make sure none of the indi stuff is started, eg.: "stop" the web manager.

**Comment by YardoDEVS** [comment]
I obtain this result, it keeps in this state forever and no window is opened:

![IMG_20210811_220449](https://user-images.githubusercontent.com/88775396/129095877-63df03c9-81c4-4229-abd8-6f6ac965f285.jpg)

**Comment by YardoDEVS** [comment]
Maybe can be that I didn't setup my geolocation info? or that is irrelevant?

**Comment by kneo** [comment]
This looks fine, the driver should work. This means you could actually connect kstars with it. Now we need to figure out why the indi web manager refuses to show the driver in the list. I come back for that ...

**Comment by YardoDEVS** [comment]
Ok, thank you so much! Then Can I use the driver in Kstarts without problem? That sounds well

**Comment by kneo** [comment]
Its supposed to work using the web management framework. I'd recommend to stick to that, since the above mentioned method is just for troubleshooting. I just wanted to make sure the driver works basically. The name in the manual is different you could check for "BRESSER Messier EXOS-2 EQ GoTo" in the list. However I need to set up new system to see what happens.

**Comment by YardoDEVS** [comment]
Yes, that name does not appear at all ... You can try it If you have a raspberry pi 4, perform a fresh install of the Astroberry Server 2.0.3 pre-cooked image, then boot connected by hdmi. I did the update of the distribution using the commands that appear on its official website, the last thing I did was install your driver for the bresser and I have the problem of the indi webmanager not showing your driver, but I am sure you will find a solution, this scenario is easy to clone

**Comment by rcreswell** [comment]
I have noticed, that on the build the execute files are installed as follows:

/usr/local/bin/indi_bresserexos2
/usr/local/share/indi/indi_bresserexos2.xml

using sudo cp you can copy them to:

/usr/bin/indi_bresserexos2
/usr/share/indi/indi_bresserexos2.xml

Restart the INDI server and the Bresser driver shows up.

I suspect that using the proper build command will prevent this from happening in the first place, e.g., follow step 5 install directions -

provideCMAKE_INSTALL_PREFIX to adjust the install location of the driver binary if necessary.
provide XML_INSTALL_DIR to adjust the location of the xml file for indi if necessary.

If you don't specify these parms and use cmake ..

Then the file copy steps above seem to bring the driver to visibility.

**Comment by kneo** [comment]
I used these paths because all the other drivers are placed there too. I don't want to litter files everywhere on the file system. I will ask where the driver files are to be placed. Instead copying the files you could also make a symbolic link as a workaround:

- `sudo ln /usr/local/bin/indi_bresserexos2 /usr/bin/indi_bresserexos2`
- `sudo ln /usr/local/share/indi/indi_bresserexos2.xml /usr/share/indi/indi_bresserexos2.xml`

This ways it gets updated, when you update the driver, also you will avoid cluttering your file system with "old files". Particularly annoying when you update stuff, and nothing changes.

**Comment by YardoDEVS** [comment]
Excellent notice! Now I just have to follow your setup guide, right? I have to put a two hour limit for the exos II in Kstars to prevent the telescope from going to the mount and breaking something right? I am Spanish and the documentation on astroberry in my language is ridiculous ... Thanks in advance! And continue with this project! This mount is one of the most affordable to start in astrophotography.

**Comment by kneo** [comment]
@YardoDEVS you should be able to set up the rest of the software stack. 

Concerning 2 hours: in general I do not recommend using the mount unattended, for now. Having a finger ready on the off switch is the best insurance for your equipment. There are some annoying quirks, for instance, loud beeping when your object moves over the meridian, you have to press a button on the hand controller to confirm the "meridian flip", which is supposed to avoid jams. I never had any fortunately. Also I figured, that I forgot to consider the time zone when updating the time. This causes some inaccuracies in pointing. I'm working on it though. However you should be able to move the scope, and track objects, when you are polar aligned. Should be good for some easy targets.

@rcreswell thanks, I try my best.

**Comment by kneo** [comment]
I found the error, its in the cmake file, for some reason the default prefix is "/usr/local" instead of just "/usr" if you are not setting it manually. This is new because my old installation resided at the expected location. I fixed it in my current development branch, ready to be merged back, when I fixed some other issues as well. For now I can only offer a work around in the form mentioned above or by doing the following:

1. **do not** use the `sudo make install` command.
2. find out where all the files are hiding using this command: `find / -name "indi_bresserexos2*" 2>/dev/null` if you already installed the driver
3. delete all driver related files located in /usr/local/ path using: `sudo rm $filename` use the output from the command above
4. open your driver build directory in a terminal
5. copy the driver files manually to the correct locations by using:

- `sudo cp indi_bresserexos2 /usr/bin/` to copy the driver binary to its install directory
- `sudo cp indi_bresserexos2.xml /usr/share/indi/` to copy the driver xml file to its install directory

after performing these steps reboot your system for good measure, the driver should appear in the indiwebmanager service list.
